### ISSUE TITLE
Improve line wrapping for long song titles

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/working-dont-bother-me#2]
@malandrina reports generating playlists of classical music can look ugly:

![screen shot 2017-08-10 at 9 55 44 am](https://user-images.githubusercontent.com/82317/29182359-339eeba8-7dc4-11e7-8262-7b38efb74ecf.png)

**Comment by malandrina** [comment]
FWIW this has been a problem with every music app I've ever used, including iTunes, Rdio and Spotify.
